version: 0.0
os: linux

files:
  - source: /
    destination: /opt/bitnami/apache/staging

# When deploying from Windows/GitHub zips, executable bits may be lost.
# Ensure hook scripts are runnable on the instance.
permissions:
  - object: /opt/bitnami/apache/staging/scripts
    pattern: "**/*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 600
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 1800
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 600
      runas: root
